# Generated by Django 2.0 on 2020-03-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_task'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='smh_task',
        ),
    ]
