# Generated by Django 2.0 on 2020-03-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200323_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(default=1)),
                ('typenames', models.CharField(max_length=32)),
                ('typesort', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'smh_tasktype',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.taskType'),
        ),
    ]
