# Generated by Django 2.0 on 2020-03-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200323_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktype',
            old_name='typenames',
            new_name='typename',
        ),
    ]
