# Generated by Django 2.0 on 2020-03-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200323_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
