# Generated by Django 2.0 on 2020-03-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200323_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hunter',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hunter', to='App.User', verbose_name='委托人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_month',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_year',
            field=models.IntegerField(default=2020, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.FileField(null=True, upload_to='task_file/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_reward',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_sketch',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='App.taskType'),
        ),
    ]
