# Generated by Django 2.0 on 2020-04-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20200328_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment_hunter',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='comment_publisher',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='App.TaskType'),
        ),
    ]
