# Generated by Django 2.0 on 2020-04-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20200406_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='App.TaskType'),
        ),
    ]
