# Generated by Django 2.0 on 2020-04-18 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20200406_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_reward',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='App.TaskType'),
        ),
    ]
