# Generated by Django 2.0.5 on 2020-05-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_received', '0003_auto_20200420_1022'),
        ('task_received', '0003_auto_20200425_1313'),
    ]

    operations = [
    ]
