# Generated by Django 2.0.5 on 2020-04-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioninfo',
            name='m_data',
            field=models.DateField(default="9999-12-31"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missioninfo',
            name='m_detail',
            field=models.CharField(default="无", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missioninfo',
            name='m_label',
            field=models.CharField(default="无", max_length=16),
            preserve_default=False,
        ),
    ]
