# Generated by Django 2.0.13 on 2020-04-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_received', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
    ]
