# Generated by Django 2.0.13 on 2020-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0028_auto_20200505_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='star',
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
