# Generated by Django 2.1.7 on 2020-05-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0037_remove_task_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='photo/2020/04/26/haha.jpg', null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
