# Generated by Django 2.0.5 on 2020-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioninfo',
            name='mission3',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missioninfo',
            name='mission4',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
