# Generated by Django 2.0.5 on 2020-04-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='code',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
