# Generated by Django 2.0.5 on 2020-04-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_auto_20200411_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32)),
                ('task_sketch', models.CharField(blank=True, max_length=512, null=True)),
                ('task_file', models.FileField(blank=True, null=True, upload_to='task_file/%Y/%m/%d/')),
                ('task_reward', models.IntegerField(blank=True, default=0, null=True)),
                ('is_pickedup', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('hunter', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hunter', to='hunt.User', verbose_name='委托人')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='hunt.User', verbose_name='发布人')),
            ],
        ),
    ]
