# Generated by Django 2.1.7 on 2020-04-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_received', '0002_remove_user_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hunter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
